baseurl         = "/"
theme           = "casper-two"
languageCode    = "en-US"
disqusShortname = ""
paginate        = 6
#SectionPagesMenu = "main"

[params]
  title       = "Sobhit kumar"
  subtitle    = "Software developer, Android developer"

  cover       = "space.jpg"
  description = "Software developer, Android developer"
  metaDescription = ""
  googleAnalytics = ""
  customCSS = []
  RSSLink = ""

  linkedinName = "sobhit-kumar"
  githubName = "mrdroid17"

  logo = ""
  orgName = "EM"
  orgWebsite = "https://www.telematika.org"
  orgDescription = "Here is a description placeholder for your org"

  author = "Sobhit Kumar"
  authorAvatar = "profile_pic.jpg"
  authorLocation = "Pune, Maharashtra"
  authorWebsite = "https://mrdroid17.github.io"
  authorDescription = "Passionate, Self motivated android developer"

  pageNotFoundTitle = "404 - Page not found"

  #casper or caspertwo
  singleViewStyle = "casper"

[permalinks]
  post = "/:slug/"

[[menu.main]]
  name = "HOME"
  url = "/"
  weight = 200

[[menu.main]]
  name = "Go"
  url = "/tags/golang/"
  weight = 100

[[menu.main]]
  name = "Life"
  url = "/categories/life"
  weight = 99

[[menu.main]]
  name = "Google"
  url = "https://google.com/"
  weight = 95